### ISSUE TITLE
Event Data property should be an object not a string

### ISSUE THREAD

**Issue by brittanyyesfit** [BadgeUp/badgeup-dotnet-client#21]
```
public class Event
    {
        public Event(string subject, string key, Modifier modifier = null, Options options = null);

        public string Id { get; set; }
        public string ApplicationId { get; set; }
        public string Subject { get; set; }
        public string Key { get; set; }
        public DateTimeOffset? Timestamp { get; set; }
        public string Data { get; set; }
        public Modifier Modifier { get; set; }
        public Options Options { get; set; }
    }

```

the documentation calls for an object: 
https://docs.badgeup.io/api/v2/endpoint/CreateEvent/

data | object | Arbitrary data that can be included to assist with achievement criteria evaluation. | false

**Comment by MarkHerhold** [comment]
Thanks for finding and reporting this issue! Fixed and published in v0.2.3. The `Data` property is now typed as `JObject`.

The event `data` field is not used in any specific product features right now and exists for end-user metadata purposes, which is why you were the first to discover the issue. Thanks!
